[package]
name = "jellycord"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.2"
http = "0.2.8"
isahc = "1.7.2"
regex = "1.6.0"
reqwest = "0.11.11"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
serenity = { version = "0.11.5", features = ["collector", "rustls_backend"] }
tokio = { version = "1.21.0", features = ["rt-multi-thread", "macros"] }
toml = "0.5.9"
sqlx = { version = "0.5.7", features = ["runtime-tokio-rustls", "sqlite", "offline"] }
chrono = "0.4.22"
